### PR TITLE
Updates to clean out stale versions and prepare for more work

### PR DESCRIPTION
**Pull request by nightscout-dl**
I don't know that this repository is being watched any more - so I've forked and spent some time simplifying and pruning the code here.

Removing the old MongoLabs upload so that all the data goes via REST API - removing menu items.

Substantially pruning code where it is over complex and unclear.

Tested so far on a Paradigm Veo 554 - with Enlite sensor.  

In Android Studio the debug builds will also allow fake data to upload so that we can start to have test cases for this.

### CODE REVIEW

**Comment by sulkaharo** [comment]
Yay for code cleaning! Wonder if it'd actually make more sense to port the relevant parts of the uploader into xDrip+, so people could just use xDrip as an uploader? Or at least that's where most of the community effort is going regarding data uploads. Second - have you checked the tuning system OpenAPS uses to find the right radio frequency? For pump communication, the tuning makes a massive difference to what the radio range is - without tuning some radio sticks only work from a distance of some centimeters, with tuning the range jumps to 5+ meters.

**Comment by sulkaharo** [comment]
Oh also, sync up with @pazaan on the codebase, I think the 640G uploader is based on this code but has cleanups

**Comment by pazaan** [comment]
@sulkaharo In the beginning the 600-series uploader was based off this codebase, but I don't think any remnants of similarity remain. The 600-series uploader has only ever uploaded via the API - never via Mongo directly.

**Comment by nightscout-dl** [comment]
Hi Sulka, Lennart - thanks for the tips - I will take a look!

**Pull request merged**
